version: "3.9"
services:
  user-app:
    container_name: 'test-user-app'
    image: 'test-user:0.0.1-SNAPSHOT'
    deploy:
      mode: global
    restart: on-failure
    environment:
      DB_URL: jdbc:mariadb://database-container/User
      DB_USR: user
      DB_PSW: password
    ports:
      - '8080:8080'  
    depends_on:
      - "database-container"
    build: .
  database-container:
    container_name: 'test-database'
    image: 'mariadb:latest'
    deploy:
      mode: global
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: User
    ports:
      - '3307:3306'
    volumes:
      - /home/andrea/Desktop/testdb/:/var/lib/mysql
networks:
  network-app:
    external: true 
