server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/User
    username: user
    password: password
    driver-class-name:  org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    serialization:
      fail-on-empty-beans: false